import { dumpContext } from '@/context/budget.ts'
import { saveMemory } from '@/memory/memdir.ts'
import { getModelProfile } from '@/provider/models.ts'
import type { ChatClient } from '@/provider/types.ts'
import { stripThinkBlocks } from '@/toolcall/parse.ts'
import type { Dirent } from 'fs'
import { readFile, readdir, stat, writeFile } from 'fs/promises'
import { extname, join, relative } from 'path'

export type InitProjectResult = {
  path: string
  memoryName: string
}

export async function initializeProject(root: string, client: ChatClient): Promise<InitProjectResult> {
  const profile = getModelProfile('coder')
  const context = await dumpContext(root, 'project overview architecture build test commands entry points coding style folder structure conventions', 8_000)
  const snapshot = await renderProjectSnapshot(root)
  const response = await client.chat(
    profile.model,
    [
      {
        role: 'system',
        content:
          'You write concise, accurate VIBE.md files that orient an AI agent to a codebase. Be literal. Never invent frameworks, scripts, directories, servers, APIs, tests, or package managers that are not shown in the supplied evidence.',
      },
      {
        role: 'user',
        content: `Using ONLY the repository evidence below, write the COMPLETE contents of a VIBE.md (GitHub-flavored markdown). This file is for future coding agents, so it should be practical and specific, not a marketing summary.

Include these sections when evidence exists:
- Project overview: what the project actually does and the main user workflow.
- Build / run / test commands: exact commands from Cargo/package scripts/visible files, plus "not configured" where absent.
- Repository structure: top-level folders/files and what each one is for.
- Architecture map: important modules/files and their responsibilities.
- Coding style and conventions: naming, module organization, error-handling patterns, UI/framework patterns, data/config formats, async/threading patterns, and test style inferred from existing code.
- Assets and configuration: sound/image/data/config files and how code refers to them.
- Development notes/gotchas: platform assumptions, generated/build directories to ignore, external tools/hardware permissions, or missing tests.
- Good first places to edit: where to change common behavior.

Rules:
- Use the "Detected project facts" and "Proven commands" sections as the source of truth for stack and commands.
- If a command is not in "Proven commands", say "not configured" or give a direct file-opening/manual workflow only when that workflow is proven.
- Do not mention frameworks, package managers, servers, APIs, directories, or files unless they appear in the file list, manifest facts, snippets, or retrieved context.
- Repository structure must mirror the supplied file list exactly. Do not move files between directories or invent tree entries.
- Do not draw an ASCII tree. Use a bullet list of exact paths copied from the file list with one short purpose each.
- If a file is listed as src/foo.rs, write src/foo.rs exactly, never foo.rs.
- For coding style, gotchas, platform assumptions, generated directories, and external permissions: if the evidence is thin, say "not enough evidence in this snapshot" rather than guessing.
- Do not mention generated/build directories such as target, dist, build, .next, or .cargo unless they appear in the file list or manifest facts.
- Be comprehensive but concise: roughly 80-160 lines for non-trivial repos, shorter for tiny repos.
- Output ONLY markdown — no wrapping code fence, no preamble.

# Deterministic Project Snapshot
${snapshot}

# Retrieved Context
${context.content}`,
      },
    ],
    profile.defaults,
  )

  const body = stripCodeFence(stripThinkBlocks(response.content)).trim()
  if (!body) throw new Error('The model produced no VIBE.md content.')

  const path = join(root, 'VIBE.md')
  await writeFile(path, `${body}\n`, 'utf8')
  await saveMemory(root, {
    name: 'project-overview',
    description: 'Project overview generated by `vibe init`',
    type: 'project',
    body: body.slice(0, 1_200),
  })
  return { path, memoryName: 'project-overview' }
}

/** Strip a single wrapping ```/```markdown fence if the model added one. */
function stripCodeFence(text: string): string {
  const match = text.match(/^```(?:markdown|md)?\n([\s\S]*?)\n```$/)
  return match?.[1] ?? text
}

const INIT_SKIP_DIRS = new Set(['.git', '.vibe', 'node_modules', 'dist', 'build', 'coverage', 'target', 'vendor'])
const SNAPSHOT_EXTENSIONS = new Set([
  '.html', '.css', '.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.json', '.md', '.txt', '.yml', '.yaml',
  '.rs', '.toml', '.py',
])
const MAX_SNAPSHOT_FILES = 160
const MAX_SNIPPET_FILES = 18
const MAX_SNIPPET_CHARS = 2_800

export async function renderProjectSnapshot(root: string): Promise<string> {
  const files = await listProjectFiles(root)
  const facts = await detectProjectFacts(root, files)
  const snippets = await readKeySnippets(root, files)
  return [
    `Files (${files.length}):`,
    ...(files.length > 0 ? files.map(file => `- ${file}`) : ['- [no files found]']),
    '',
    'Detected project facts:',
    facts.facts.length > 0 ? facts.facts.map(fact => `- ${fact}`).join('\n') : '- [none detected]',
    '',
    'Proven commands:',
    facts.commands.length > 0 ? facts.commands.map(command => `- ${command}`).join('\n') : '- [no build/run/test commands proven]',
    '',
    'Key file excerpts:',
    snippets.length > 0 ? snippets.join('\n\n') : '[no small text files available]',
  ].join('\n')
}

async function listProjectFiles(root: string): Promise<string[]> {
  const out: string[] = []
  await walk(root, 0, async path => {
    if (out.length >= MAX_SNAPSHOT_FILES) return
    out.push(relative(root, path).split('\\').join('/'))
  })
  return out.sort()
}

async function walk(dir: string, depth: number, visit: (file: string) => Promise<void>): Promise<void> {
  if (depth > 5) return
  let entries: Dirent[]
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const entry of entries) {
    if (entry.isSymbolicLink()) continue
    if (entry.isDirectory()) {
      if (entry.name.startsWith('.') || INIT_SKIP_DIRS.has(entry.name)) continue
      await walk(join(dir, entry.name), depth + 1, visit)
      continue
    }
    if (!entry.isFile()) continue
    const full = join(dir, entry.name)
    try {
      if ((await stat(full)).size <= 250_000) await visit(full)
    } catch {
      // Ignore unreadable files in the orientation snapshot.
    }
  }
}

async function readPackageJson(root: string): Promise<{ name?: string; scripts?: Record<string, string> } | undefined> {
  try {
    const parsed = JSON.parse(await readFile(join(root, 'package.json'), 'utf8')) as { name?: string; scripts?: Record<string, string> }
    return parsed
  } catch {
    return undefined
  }
}

async function readKeySnippets(root: string, files: string[]): Promise<string[]> {
  const selected = files
    .filter(file => SNAPSHOT_EXTENSIONS.has(extname(file).toLowerCase()))
    .sort((a, b) => snippetPriority(a) - snippetPriority(b) || a.localeCompare(b))
    .slice(0, MAX_SNIPPET_FILES)

  const snippets: string[] = []
  for (const file of selected) {
    try {
      const content = await readFile(join(root, file), 'utf8')
      snippets.push(`## ${file}\n\`\`\`\n${content.slice(0, MAX_SNIPPET_CHARS)}${content.length > MAX_SNIPPET_CHARS ? '\n... (truncated)' : ''}\n\`\`\``)
    } catch {
      // Ignore unreadable files.
    }
  }
  return snippets
}

function snippetPriority(file: string): number {
  if (file === 'package.json') return 0
  if (file === 'Cargo.toml') return 0
  if (/^readme\.md$/i.test(file)) return 1
  if (file === 'index.html') return 2
  if (file === 'src/main.rs' || file === 'src/lib.rs') return 2
  if (/vite\.config|next\.config|astro\.config|svelte\.config/i.test(file)) return 3
  if (file.endsWith('.toml') || file.endsWith('.json')) return 3
  if (file.startsWith('src/')) return 4
  return 5
}

type ProjectFacts = { facts: string[]; commands: string[] }

async function detectProjectFacts(root: string, files: string[]): Promise<ProjectFacts> {
  const facts: string[] = []
  const commands: string[] = []
  const has = (path: string) => files.includes(path)

  if (has('package.json')) {
    const packageJson = await readPackageJson(root)
    facts.push('Node/JavaScript project: package.json present')
    if (packageJson?.name) facts.push(`package name: ${packageJson.name}`)
    const scripts = packageJson?.scripts ?? {}
    for (const [name, command] of Object.entries(scripts)) commands.push(`${name}: npm run ${name}  # ${command}`)
    if (has('bun.lock') || has('bun.lockb')) facts.push('Bun lockfile present')
    if (has('pnpm-lock.yaml')) facts.push('pnpm lockfile present')
    if (has('yarn.lock')) facts.push('Yarn lockfile present')
  }

  if (has('Cargo.toml')) {
    const cargoToml = await readFile(join(root, 'Cargo.toml'), 'utf8').catch(() => '')
    facts.push('Rust/Cargo project: Cargo.toml present')
    for (const line of summarizeTomlPackage(cargoToml)) facts.push(line)
    commands.push('build: cargo build')
    commands.push('run: cargo run')
    commands.push('test: cargo test')
  }

  if (has('pyproject.toml') || has('requirements.txt') || has('setup.py')) {
    facts.push('Python project: Python manifest/dependency file present')
    if (has('pyproject.toml')) commands.push('install: python -m pip install -e .')
    if (has('requirements.txt')) commands.push('install dependencies: python -m pip install -r requirements.txt')
    commands.push('test: pytest  # if pytest is configured/installed')
  }

  if (has('go.mod')) {
    const moduleLine = (await readFile(join(root, 'go.mod'), 'utf8').catch(() => '')).split('\n').find(line => line.startsWith('module '))
    facts.push(`Go module: ${moduleLine?.replace(/^module\s+/, '') || 'go.mod present'}`)
    commands.push('build: go build ./...')
    commands.push('test: go test ./...')
    commands.push('run: go run .')
  }

  if (has('Makefile') || has('makefile')) {
    facts.push('Makefile present')
    commands.push('make: make')
  }

  if (has('pom.xml')) {
    facts.push('Maven Java project: pom.xml present')
    commands.push('build/test: mvn test')
    commands.push('package: mvn package')
  }

  if (has('build.gradle') || has('build.gradle.kts')) {
    facts.push('Gradle project: build.gradle present')
    commands.push('build: ./gradlew build  # or gradle build if wrapper is absent')
    commands.push('test: ./gradlew test  # or gradle test if wrapper is absent')
  }

  if (has('index.html') && !has('package.json')) {
    facts.push('Static web entrypoint: index.html present without package.json')
    commands.push('run: open index.html in a browser')
  }

  if (files.some(file => file.startsWith('src/'))) facts.push('source directory: src/')
  if (files.some(file => /(^|\/)(test|tests|__tests__)(\/|$)/.test(file) || /\.(test|spec)\./.test(file))) facts.push('tests detected in file tree')
  if (files.some(file => /\.(png|jpg|jpeg|gif|webp|wav|mp3|ogg|flac)$/i.test(file))) facts.push('media/assets detected in file tree')
  if (files.some(file => /\.(json|toml|yaml|yml)$/i.test(file))) facts.push('structured config/data files detected')

  return { facts: [...new Set(facts)], commands: [...new Set(commands)] }
}

function summarizeTomlPackage(content: string): string[] {
  return content
    .split('\n')
    .map(line => line.trim())
    .filter(line => /^(name|version|edition)\s*=/.test(line))
    .map(line => `Cargo ${line}`)
}
